/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

plugins {
     // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building a CLI application
    application
    // Comunity plugins
    id("org.springframework.boot") version "2.1.7.RELEASE"
    id("io.spring.dependency-management") version "1.0.8.RELEASE"
    id("maven-publish")
    id("io.freefair.lombok") version "4.0.1"
}

group = "com.queli.graphql"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8


repositories {
  mavenCentral()
}

dependencies {
  compile("org.springframework.boot:spring-boot-starter-web")
  compile("org.springframework.boot:spring-boot-starter-data-jpa")
  compile("com.graphql-java:graphql-spring-boot-starter:5.0.2")
  compile("com.graphql-java:graphql-java-tools:5.2.4")
  compile("com.graphql-java:graphiql-spring-boot-starter:5.0.2")
  runtime("com.h2database:h2")
  // Finally, I use lombok as plugin
  // compileOnly("org.projectlombok:lombok")
  // annotationProcessor("org.projectlombok:lombok")
}

tasks.bootJar {
    archiveName = "app.jar"
    mainClassName = "${project.group}.Application"
}

tasks.bootRun {
    main = "${project.group}.Application"
}
